### ISSUE TITLE
Help with adjustments

### ISSUE THREAD

**Issue by ashtastic** [ashtastic/dsn1675-project-1#1]
Hey @thomasjbradley,

I was wondering if you could give me a hint as to how I could go about coding for the heading part of my website. So, originally I had my display picture (.dp) in a div with my h1 and donut picture. I made my .dp display: absolute and adjusted the position coordinates, but I was having issues having my .intro div flowing with the picture. I figured it out when I started my media queries. The .dp flows over top of the text in my .intro and I have to readjust the size of the .dp and the padding on the p in the .intro every 10 or 15px. It's a bit ridiculous. But I don't know how to have the .dp appear overtop of the bottom of the donut picture and top of the .intro without constantly messing with the p in the .intro as the screen size increases... ideally, I think the .dp needs to be in the .intro div so that the spacing between it and the intro p stay the same, but then I can't figure out how to float the .dp about the top of the .intro...

Any idea on how I can work around this?

**Comment by thomasjbradley** [comment]
Yeah, I think putting the `.dp` in `.intro` makes sense. Then you could use `margin-top` with a negative value (instead of `position: absolute`) to pull the `.dp` image up to overlap the doughnuts... that should work a little more consistently.
