### ISSUE TITLE
iPhone 4 browser testing Problems

### ISSUE THREAD

**Issue by ashtastic** [ashtastic/dsn1675-project-1#7]
Hi @thomasjbradley,

I finished my website, tested it and checked off all the things on the Launch checklist. Everything checks out except when I tested my website on my iPhone 4. The space around my social media icons are enormous, and my donut.jpg doesn't show up. Doesn't matter what browser I check it in... Chrome, Safari or Opera. Maybe it has something to do with the svgs in the html or my media queries? I looked in the tutorials and couldn't find anything. Could you take a look? My project is ready to be handed in. It's just this one problem. 

Thank you :)

**Comment by ashtastic** [comment]
Hey @thomasjbradley,

So I adjusted the width and height on the svgs (actually put them as min values so that they adjust to the css, which works out great on desktop) and still nothing. I got them to show once after 50 some odd refreshes, but nothing since. I made a few attempts at putting some overflow:hidden and display:blocks to help, but still nothing.

This is a real stumper.

**Comment by thomasjbradley** [comment]
There aren't actually `min-width` and height attributes for SVG.
Did they not work with just `width` and `height`?

**Comment by ashtastic** [comment]
It actually worked!! I'm not joking, yesterday I didn't have the min values and it still didn't work. I just removed them and it works. I just need to do some adjustments in css to have them size properly across the media queries.

K, so next is my background image on the masthead (donuts.jpg). It doesn't show up. I tried putting `display: block` and `overflow: hidden` on the masthead, and tried it on the `.h1` and still nothing.

I have learned a valuable lesson to always check iphone 4, cause my goodness its got attitude.

**Comment by thomasjbradley** [comment]
Can I see a screenshot of what it's doing?

**Comment by ashtastic** [comment]
![photo](https://cloud.githubusercontent.com/assets/10467656/10436839/00f86354-70f7-11e5-867e-94495adbda3f.PNG)

**Comment by thomasjbradley** [comment]
We need to confirm if the background image isn't loading or if it's just too big.

Set a background colour on the `.masthead` and test to see if it stays white, or if you can see the background colour.

**Comment by ashtastic** [comment]
The change in colour worked, no problem. I thought maybe it could be the size of the image, so I brought it down to a quality of 0 (181KB) and it still doesn't show.
![photo 1](https://cloud.githubusercontent.com/assets/10467656/10440487/a024e0fe-710d-11e5-89c5-b66fbc0cde22.PNG)

**Comment by thomasjbradley** [comment]
Did you remove the background image?
I would like to have both the background image and the colour to determine which one we see.

**Comment by ashtastic** [comment]
Looks the exact same with both the background image AND the background colour on the masthead. I also notice that the `h1` looks doubled. See how it almost as a shadow? It's not supposed to look like that, and it doesn't look like that on other mobiles I've checked it on. Could the ios 7 be doubling the masthead or the `h1` somehow?

![photo 1](https://cloud.githubusercontent.com/assets/10467656/10441436/a21a8e6e-7116-11e5-8aa7-7289e4e30967.PNG)

**Comment by thomasjbradley** [comment]
Okay... so, the background image just isn't loading then... huh.

I know that older devices used to have a memory limit on how big websites could be... maybe we're running into that. 

Maybe try, just to test, making the image dimensions much smaller and see if it shows up, like 320px wide or something.

**Comment by ashtastic** [comment]
Yep that worked!! Thank you very much for all your help :)
